### ISSUE TITLE
Desktop display issues with picom

### ISSUE THREAD

**Issue by xxxserxxx** [LandingEllipse/kitti3#8]
- kitti3 0.2.4
- kitty 0.16.0
- i3 version 4.18 (gaps)
- picom v7.5
- xorg-server 1.20.7-1
- X display driver: intel

This is recent(ish) behavior; maybe within the past week.  When I first noticed this was after a system update, and every package *but* kitti3 may have been updated; in that list, only kitti3 is manually installed, and I just updated it this morning to try to fix the issue. 

kitti3 will open on the left external display reliably.  It will not *show* on the right display, but I can tell by the other windows dimming that picom thinks it's got another window to show. I can get it to show on the right display if I perform the following magic: show on left; hotkey switch to right; hide & show kitti3 again -- but then it'll **only** show on either the left or the right; if I switch to the middle, it just opens on the right again.  If I switch left and close/open kitti3, then I can get it to open on the middle.  It only ever opens in that "there, but hidden" state on the right screen.

All behavior is normal when `picom` is killed, and then kitti3 opens on the correct display whichever that is.

**Only** kitti3 is getting this treatment.  All other windows (including floating ones) correctly show up on whichever display has focus.

Output of `xrandr -q`, trimming the unused modes:
```
Screen 0: minimum 8 x 8, current 5760 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 290mm x 160mm
   1920x1080     60.03*+  48.03  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
DP2-1 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 520mm x 290mm
   1920x1080     60.00*+  50.00    59.94  
DP2-2 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 520mm x 290mm
   1920x1080     60.00*+  50.00    59.94  
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

**Comment by LandingEllipse** [comment]
Hi xxxserxxx,

Thanks for submitting this issue. It's a strange one for sure... I don't use picom myself, but I'll install it and see if I can recreate it. Might be a few days though, as I need to source an extra display adapter to get three screens up and running, and carve out a time slot.

In the meantime, if you're interested, capable, and have some spare time to kill, then it would be nice if you could look at some debug output (just some ideas off the top of my head that I'll try when/if I'm able to reproduce this):

-  If picom supports a verbose mode, enable and check if it throws any complaints you way when the issue is triggered
- Check for any logged errors with e.g. `journalctl -f` (slim chance there, but worth a shot)
- Use `i3-msg` to listen for i3wm IPC events. While it's a bit of a wall of JSON, I'd perhaps start with something like `i3-msg -m -t subscribe '[ "window" ]` (_spit out all events associated with windows_) and see what you find - specifically if there are any differences between toggling kitti3 with and without picom enabled. The output can be parsed pretty effectively for sanity with `jq`, e.g.: `jq '.container.scratchpad_state' <(i3-msg -m -t subscribe '[ "window" ]')`

If I don't get back to you in a sensible time frame, please don't hesitate to ping me again.

**Comment by xxxserxxx** [comment]
No problem.  I'm out next week myself, and am responding slowly.

Happy to do tests!  I'll post the results here.

I've since noticed the pattern; it's much more simple than I originally reported.

- App on display 1 focused: kitti3 always shows on display 1
- App on display 2 focused: kitti3 always shows on display 3
- App on display 3 focused: kitti3 opens hidden, on no display.

I strongly suspect that something is getting confused about the geometry.  The kitti3 window correctly recognizes the right edge of the left display; thinks the right edge of the center is the right display; and probably (because the window isn't visible) thinks the right edge of the right display is waaaaay off to the right.

I think the i3-msg debugging is probably going to be the most informative.

**Comment by xxxserxxx** [comment]
Ok.  I haven't spent much time looking at this yet, but I've annotated it with each of the steps.

[debug.txt](https://github.com/LandingEllipse/kitti3/files/4288552/debug.txt)

**Comment by xxxserxxx** [comment]
I'm not sure what this does except confirm suspicions, but digging through the log reveals:

Premise(s)/facts:
- All screens are the same width: 1920
   - The kitti3 offset is 768.
   - The kitti3 windows are 1152 wide.
   - So: 1152 + 768 = 1920, the width of one screen
- The origin of all coordinates (0,0) is from the left-edge of the left screen
- Therefore: opening on the middle screen should be left-width + offset, or 1920 + 768 = 2688

Now, looking at the log, we see that the attempt to open on the middle screen opens the window at x=4608

- This is the same as 2*1920 + 768, exactly the right spot on the **rightmost** screen
- Looking at the following "move" block, kitti3 is opening at 8448, which is far to the right of the rightmost display.  
- This number corresponds to an imaginary 4th display (4*1920 + 768 = 8448)

Also, I lied.  I just killed picom again and kitti3 is behaving in the same incorrect way.  Maybe running picom messes up the geometry, but unless it's that, picom was a red herring and is not related to the issue.

I want to restate that I've not seen this behavior with any other floating windows, or windows that I've moved to the scratchpad and back.  These all position normally.

**Comment by LandingEllipse** [comment]
Hi again xxxserxxx,

I hope you're doing well. Thank you for your patience; I'm not going to blame the pandemic for the delayed resolution to this, but the mayhem certainly hasn't helped...

I finally got around to reproducing this issue on my system when I set up my home office, and believe that I have found a fix. To be honest I still don't know exactly what the root cause was/is, but it seems the i3wm devs made some changes to the way scratchpad move to position commands were handled in the 4.18 release, so this might just have been an unintended side-effect. The fix took a while to arrive at, but is actually trivial: move Kitty out of the scratch pad before resizing/repositioning rather than after. The original order was chosen to guard against visual flickering, but it seems at least on my i915 meh-GPU system driving a 4k and two 2k5 monitors that everything's still running smooth - possibly because everything's still sent as a single IPC request.

Anyway, I've uploaded the latest 0.2.6 release of kitti3 to PYPI. If you're still interested then please take it for a test run and let me know how it goes.

Many thanks for flagging this in the first place, and for donating your time to providing the debug logs.

All the best,
Ariel

**Comment by xxxserxxx** [comment]
My pleasure.  Thanks for tracking it down and fixing it.
